version: '3'
services:
  db:
    restart: always
    image: postgres:9.4.12-alpine
    volumes:
      - sql-data:/var/lib/postgresql/data
  web:
    build: .
    command: sh -c 'rm /myapp/tmp/pids/* || true && bundle exec rails s -p 3000 -b 0.0.0.0'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  sql-data:
    driver: local
