version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      - run: echo "hello world"
