version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu
        - RAILS_ENV=test
        - RACK_ENV=test
      - image: postgres:9.5
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=myapp_test
    working_directory: ~/myapp

    steps:
      - run:
          name: Install docker
          command: |
            set -x
            VERSION="17.03.0-ce"
            curl -L -o /tmp/docker-$VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$VERSION.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
            chmod +x  /usr/bin/docker-compose
      - setup-docker-engine:
          reusable: true
          exclusive: true
      - run:
          name: Setup
          command: |
            set -x
            docker build . -t dayservice-navi --pull
            docker-compose down -v
            docker-compose build --pull
            docker-compose up -d
            docker-compose run web ruby -e "sleep 1 until system %q(psql -h 'db' -U 'postgres' -c '\l' > /dev/null)"
            docker-compose run web bin/setup
      - run:
          name: Test
          command: |
            set -x
            docker-compose run -e DISABLE_SPRING=true web bin/rails test
            docker-compose run web bundle exec cucumber
            docker-compose run web bundle exec rubocop
            docker-compose run web npm run lint



      # Save test results for timing analysis
      - store_test_results:
          path: test_results
