version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/app
    # ここは1.0でもあった実行対象ブランチ設定
    branches:
      only:
        - master

    # Dockerのimage設定はここで 今回はruby2.4.1とdatabaseにはpostgresql9.6.2(公式image)を利用
    docker:
      - image: ruby:2.4.1
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: root
    steps:
      - checkout
      - run: echo "hello world"
